[env:esp32-c6-devkitm-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino

lib_deps =
    olikraus/U8g2@^2.35.31

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

monitor_speed = 115200
monitor_dtr = 1
monitor_rts = 1

; esptool detected your actual flash as 8 MB
board_upload.flash_size = 8MB
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
